services:
    reverbtest-php1:
        container_name: reverbtest-php1
        image: reverbtest-php1
        build:
            context: .
            dockerfile: ./docker/php/Dockerfile
            args:
                WWWGROUP: "${WWWGROUP}"
        extra_hosts:
            - "host.docker.internal:host-gateway"
        ports:
            - "80:80"
            - "5173:5173"
        environment:
            WWWUSER: "${WWWUSER}"
            LARAVEL_SAIL: 1
            XDEBUG_MODE: "${SAIL_XDEBUG_MODE:-off}"
            XDEBUG_CONFIG: "${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}"
            IGNITION_LOCAL_SITES_PATH: "${PWD}"
        volumes:
            - ".:/var/www/html"
        networks:
            - reverbtest-network
        depends_on:
            - reverbtest-pgsql
            - reverbtest-redis
            - reverbtest-minio
            - reverbtest-mailpit

    reverbtest-pgsql:
        container_name: reverbtest-pgsql
        image: "postgres:17"
        ports:
            - "5432:5432"
        environment:
            PGPASSWORD: password
            POSTGRES_DB: laravel
            POSTGRES_USER: sail
            POSTGRES_PASSWORD: password
        volumes:
            - "reverbtest-pgsql:/var/lib/postgresql/data"
            - "./docker/pgsql/create-testing-database.sql:/docker-entrypoint-initdb.d/10-create-testing-database.sql"
        networks:
            - reverbtest-network
        healthcheck:
            test:
                - CMD
                - pg_isready
                - "-q"
                - "-d"
                - "${DB_DATABASE}"
                - "-U"
                - "${DB_USERNAME}"
            retries: 3
            timeout: 5s

    reverbtest-redis:
        container_name: reverbtest-redis
        image: "redis:alpine"
        ports:
            - "6379:6379"
        volumes:
            - "reverbtest-redis:/data"
        networks:
            - reverbtest-network
        healthcheck:
            test:
                - CMD
                - redis-cli
                - ping
            retries: 3
            timeout: 5s

    reverbtest-minio:
        container_name: reverbtest-minio
        image: "minio/minio:latest"
        ports:
            - "9000:9000"
            - "8900:8900"
        environment:
            MINIO_ROOT_USER: reverbtest
            MINIO_ROOT_PASSWORD: password
        volumes:
            - "reverbtest-minio:/data"
        networks:
            - reverbtest-network
        command: 'minio server /data --console-address ":8900"'
        healthcheck:
            test:
                - CMD
                - mc
                - ready
                - local
            retries: 3
            timeout: 5s

    reverbtest-mailpit:
        container_name: reverbtest-mailpit
        image: "axllent/mailpit:latest"
        ports:
            - "1025:1025"
            - "8025:8025"
        networks:
            - reverbtest-network

networks:
    reverbtest-network:
        external: true

volumes:
    reverbtest-pgsql:
        driver: local
    reverbtest-redis:
        driver: local
    reverbtest-minio:
        driver: local
