services:
    reverbtest-php2:
        container_name: reverbtest-php2
        image: reverbtest-php2
        build:
            context: .
            dockerfile: ./docker/php/Dockerfile
            args:
                WWWGROUP: "${WWWGROUP}"
        extra_hosts:
            - "host.docker.internal:host-gateway"
        ports:
            - "81:80"
            - "5174:5173"
        environment:
            WWWUSER: "${WWWUSER}"
            LARAVEL_SAIL: 1
            XDEBUG_MODE: "${SAIL_XDEBUG_MODE:-off}"
            XDEBUG_CONFIG: "${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}"
            IGNITION_LOCAL_SITES_PATH: "${PWD}"
        volumes:
            - ".:/var/www/html"
        networks:
            - reverbtest-network

networks:
    reverbtest-network:
        external: true
